# Generated by Django 5.2.4 on 2025-07-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Создай свой дневник', max_length=255, unique=True, verbose_name='Название дневника')),
            ],
            options={
                'verbose_name': 'Дневник',
                'verbose_name_plural': 'Дневники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Введите заголовок для вашей заметки', max_length=255, null=True, verbose_name='Заголовок заметки')),
                ('content', models.TextField(help_text='Тут вы можете написать свои мысли, события дня или что-то важное', verbose_name='Запись')),
                ('image', models.ImageField(blank=True, help_text='Можете добавить изображение к заметке', null=True, upload_to='notes/images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заметки', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления заметки', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-created_at'],
            },
        ),
    ]
