# Generated by Django 5.2.4 on 2025-07-28 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, которому принадлежит дневник', on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='notes',
            name='diary',
            field=models.ForeignKey(help_text='Дневник, к которому принадлежит заметка', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='diary.diary', verbose_name='Дневник'),
        ),
    ]
