# Generated by Django 5.2.4 on 2025-07-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания дневника', null=True, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='notes',
            name='event_date',
            field=models.DateField(blank=True, help_text='Введите дату события, если необходимо', null=True, verbose_name='Дата события'),
        ),
    ]
